USE db_users;

INSERT INTO FieldActivity (Name) VALUES ('B2B-услуги');
INSERT INTO FieldActivity (Name) VALUES ('Автоматизация бизнеса');
INSERT INTO FieldActivity (Name) VALUES ('Автосервис');
INSERT INTO FieldActivity (Name) VALUES ('Автотовары');
INSERT INTO FieldActivity (Name) VALUES ('Автотранспорт');
INSERT INTO FieldActivity (Name) VALUES ('Безопасность');
INSERT INTO FieldActivity (Name) VALUES ('Бизнес-услуги');
INSERT INTO FieldActivity (Name) VALUES ('Бытовые услуги');
INSERT INTO FieldActivity (Name) VALUES ('Власть');
INSERT INTO FieldActivity (Name) VALUES ('Государственное управление');
INSERT INTO FieldActivity (Name) VALUES ('Двери');
INSERT INTO FieldActivity (Name) VALUES ('Детские сады');
INSERT INTO FieldActivity (Name) VALUES ('Детские товары');
INSERT INTO FieldActivity (Name) VALUES ('Дополнительное образование');
INSERT INTO FieldActivity (Name) VALUES ('Жилищно-коммунальные услуги');
INSERT INTO FieldActivity (Name) VALUES ('Запчасти');
INSERT INTO FieldActivity (Name) VALUES ('Инструмент');
INSERT INTO FieldActivity (Name) VALUES ('Канцтовары и книги');
INSERT INTO FieldActivity (Name) VALUES ('Красота');
INSERT INTO FieldActivity (Name) VALUES ('Культура');
INSERT INTO FieldActivity (Name) VALUES ('Мебель');
INSERT INTO FieldActivity (Name) VALUES ('Медицина');
INSERT INTO FieldActivity (Name) VALUES ('Медтовары');
INSERT INTO FieldActivity (Name) VALUES ('Металлы');
INSERT INTO FieldActivity (Name) VALUES ('Напитки');
INSERT INTO FieldActivity (Name) VALUES ('Недвижимость');
INSERT INTO FieldActivity (Name) VALUES ('Оборудование для сферы услуг');
INSERT INTO FieldActivity (Name) VALUES ('Образование');
INSERT INTO FieldActivity (Name) VALUES ('Обувь');
INSERT INTO FieldActivity (Name) VALUES ('Одежда');
INSERT INTO FieldActivity (Name) VALUES ('Организация праздников');
INSERT INTO FieldActivity (Name) VALUES ('Остальное');
INSERT INTO FieldActivity (Name) VALUES ('Перевозки');
INSERT INTO FieldActivity (Name) VALUES ('Поесть');
INSERT INTO FieldActivity (Name) VALUES ('Полиграфии');
INSERT INTO FieldActivity (Name) VALUES ('Правоохранительные органы');
INSERT INTO FieldActivity (Name) VALUES ('Продукты');
INSERT INTO FieldActivity (Name) VALUES ('Промышленное оборудование');
INSERT INTO FieldActivity (Name) VALUES ('Профессиональное образование');
INSERT INTO FieldActivity (Name) VALUES ('Развлечения');
INSERT INTO FieldActivity (Name) VALUES ('Реклама');
INSERT INTO FieldActivity (Name) VALUES ('Религия');
INSERT INTO FieldActivity (Name) VALUES ('Ремонт, стройка');
INSERT INTO FieldActivity (Name) VALUES ('Сантехника');
INSERT INTO FieldActivity (Name) VALUES ('Социальные услуги');
INSERT INTO FieldActivity (Name) VALUES ('Спецмагазины');
INSERT INTO FieldActivity (Name) VALUES ('Спорт');
INSERT INTO FieldActivity (Name) VALUES ('Спортивные комплексы');
INSERT INTO FieldActivity (Name) VALUES ('Спорттовары');
INSERT INTO FieldActivity (Name) VALUES ('Среднее образование');
INSERT INTO FieldActivity (Name) VALUES ('Строительные услуги');
INSERT INTO FieldActivity (Name) VALUES ('Сувениры');
INSERT INTO FieldActivity (Name) VALUES ('Тара и упаковка');
INSERT INTO FieldActivity (Name) VALUES ('Творчество и досуг');
INSERT INTO FieldActivity (Name) VALUES ('Текстиль');
INSERT INTO FieldActivity (Name) VALUES ('Техника');
INSERT INTO FieldActivity (Name) VALUES ('Товары для животных');
INSERT INTO FieldActivity (Name) VALUES ('Топливо');
INSERT INTO FieldActivity (Name) VALUES ('Торговое оборудование');
INSERT INTO FieldActivity (Name) VALUES ('Торговые центры');
INSERT INTO FieldActivity (Name) VALUES ('Транспорт');
INSERT INTO FieldActivity (Name) VALUES ('Туризм');
INSERT INTO FieldActivity (Name) VALUES ('Услуги');
INSERT INTO FieldActivity (Name) VALUES ('Финансовые услуги');
INSERT INTO FieldActivity (Name) VALUES ('Химия и вторсырьё');
INSERT INTO FieldActivity (Name) VALUES ('Хозяйственные товары');
INSERT INTO FieldActivity (Name) VALUES ('Цветы');
INSERT INTO FieldActivity (Name) VALUES ('Экстренные службы');
INSERT INTO FieldActivity (Name) VALUES ('Ювелирные изделия');
INSERT INTO FieldActivity (Name) VALUES ('Юридические услуги');
