USE db_users;

INSERT INTO City (Name) VALUES ('Подмаячный');
INSERT INTO City (Name) VALUES ('Нижнесакмарский');
INSERT INTO City (Name) VALUES ('Пруды');
INSERT INTO City (Name) VALUES ('Краснохолм');
INSERT INTO City (Name) VALUES ('Нежинка');
INSERT INTO City (Name) VALUES ('Городище');
INSERT INTO City (Name) VALUES ('"поселок имени Куйбышева"');
INSERT INTO City (Name) VALUES ('Подгородняя Покровка');
INSERT INTO City (Name) VALUES ('Сакмарский');
INSERT INTO City (Name) VALUES ('Каргала');
INSERT INTO City (Name) VALUES ('Заречный');
INSERT INTO City (Name) VALUES ('Холодные Ключи');
INSERT INTO City (Name) VALUES ('Пристанционный');
INSERT INTO City (Name) VALUES ('"18 разъезд"');
INSERT INTO City (Name) VALUES ('"Солнечный"');
INSERT INTO City (Name) VALUES ('Пригородный');
INSERT INTO City (Name) VALUES ('Южный');
INSERT INTO City (Name) VALUES ('Сакмара');
INSERT INTO City (Name) VALUES ('Весенний');
INSERT INTO City (Name) VALUES ('Караванный');
INSERT INTO City (Name) VALUES ('Бердянка');
INSERT INTO City (Name) VALUES ('Самородово');
INSERT INTO City (Name) VALUES ('"поселок Ростоши"');
INSERT INTO City (Name) VALUES ('"Ростошинские пруды"');
INSERT INTO City (Name) VALUES ('Красный Партизан');
INSERT INTO City (Name) VALUES ('Троицкий');
INSERT INTO City (Name) VALUES ('"поселок Кушкуль"');
INSERT INTO City (Name) VALUES ('"Северные ворота"');
INSERT INTO City (Name) VALUES ('"ДНТСН "Лидиния"');
INSERT INTO City (Name) VALUES ('"ТСН "Строитель"');
INSERT INTO City (Name) VALUES ('"СНТ "Незабудка"');
INSERT INTO City (Name) VALUES ('"СНТСТ "Магистраль-2"');
INSERT INTO City (Name) VALUES ('"СНТСН "Фармация"');
INSERT INTO City (Name) VALUES ('"СНТ "Пищевик"');
INSERT INTO City (Name) VALUES ('"СНТ "Конверсия"');
INSERT INTO City (Name) VALUES ('"СНТ "Просвещение"');
INSERT INTO City (Name) VALUES ('"СНТ "Спутник"');
INSERT INTO City (Name) VALUES ('"ДНТСН "Медик"');
INSERT INTO City (Name) VALUES ('"Нефтехимик"');
INSERT INTO City (Name) VALUES ('"Импульс"');
INSERT INTO City (Name) VALUES ('"Полянка"');
INSERT INTO City (Name) VALUES ('Оренбург');